### ISSUE TITLE
Raspberry Pi tutorials

### ISSUE THREAD

**Issue by qwertywelch** [MySystemName/msn-docs#1]
Each team member should complete basic tutorials for setting up a Raspberry Pi system and write a sample Java program for communicating with the GPIO pins using the Pi4J library.

OS: https://www.raspberrypi.org/downloads/raspbian/
Etcher: https://etcher.io/

https://thepihut.com/blogs/raspberry-pi-tutorials/27968772-turning-on-an-led-with-your-raspberry-pis-gpio-pins

**Comment by qwertywelch** [comment]
Once y'all have done these, comment here. Last one to finish should close this issue 👍

**Comment by Zax212** [comment]
Done 1/26/18

**Comment by remicktr** [comment]
Done with Nick a few days ago.
